from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from kernel_evaluator.db.ops import (
    get_best_kernel_by_function_and_scalars,
    get_best_kernel_for_spec_json,
    get_kernel,
    insert_external_kernel,
    invalidate_kernel,
    update_kernel_postprocessing,
)
from kernel_evaluator.services.api_keys import ApiPrincipal, require_admin_key, require_api_key


def apply_overhead(raw_speedup: float, overhead_pct: float) -> float:
    return raw_speedup * (1 + overhead_pct / 100)


class ExternalKernelRequest(BaseModel):
    """Request body for inserting an external kernel."""
    kernel_source: str = Field(..., description="Kernel source code")
    kernel_us: float = Field(..., description="Kernel execution time in microseconds")
    baseline_us: float = Field(..., description="Baseline execution time in microseconds")
    plugin: str = Field(..., description="Plugin name (e.g. 'cublas', 'flash_attn')")
    spec_json: dict = Field(..., description="Kernel spec JSON")
    function_name: str = Field(..., description="Function name")
    scalar_args: Optional[dict] = Field(default=None, description="Scalar arguments")
    gpu: str = Field(default="h100", description="GPU type")
    postprocessed_source: Optional[str] = Field(default=None, description="Postprocessed kernel source")
    python_registration: Optional[str] = Field(default=None, description="Python registration code")

kernels_router = APIRouter(prefix="/kernels", tags=["kernels"])


@kernels_router.get("/best")
def get_best_kernel_route(
    function_name: Optional[str] = None,
    scalar_args: Optional[str] = None,
    spec_json: Optional[str] = None,
    gpu: str = "h100",
    _principal: ApiPrincipal = Depends(require_api_key),
):
    """Get the best kernel for inliner/TKCC.

    Query by either:
    - function_name + scalar_args: lookup by function name and scalar parameters
    - spec_json: lookup by full spec JSON
    """
    import json

    if spec_json is not None:
        # Lookup by spec_json
        try:
            spec_json_dict = json.loads(spec_json)
        except json.JSONDecodeError as e:
            raise HTTPException(400, f"Invalid spec_json: {e}")
        result = get_best_kernel_for_spec_json(spec_json_dict, gpu)
        if result is None:
            raise HTTPException(404, f"No kernel for spec_json={spec_json}")
    elif function_name is not None and scalar_args is not None:
        # Lookup by function_name + scalar_args
        try:
            scalar_args_dict = json.loads(scalar_args)
        except json.JSONDecodeError as e:
            raise HTTPException(400, f"Invalid scalar_args JSON: {e}")
        result = get_best_kernel_by_function_and_scalars(function_name, scalar_args_dict, gpu)
        if result is None:
            raise HTTPException(404, f"No kernel for {function_name} with {scalar_args}")
    else:
        raise HTTPException(400, "Provide either spec_json OR (function_name + scalar_args)")

    kernel, run = result
    return {
        "id": kernel.id,
        "function_name": run.function_name,
        "scalar_args": run.scalar_args,
        "spec_json": run.spec_json,
        "kernel_source": kernel.kernel_source,
        "postprocessed_source": kernel.postprocessed_source,
        "python_registration": kernel.python_registration,
        "kernel_us": kernel.kernel_us,
        "baseline_us": kernel.baseline_us,
        "speedup": kernel.baseline_us / kernel.kernel_us,
        "gpu": run.gpu,
    }


@kernels_router.post("/external")
def insert_external_kernel_route(
    req: ExternalKernelRequest,
    _principal: ApiPrincipal = Depends(require_admin_key),
):
    """Insert an external kernel not generated by the evaluation system."""
    kernel = insert_external_kernel(
        kernel_source=req.kernel_source,
        kernel_us=req.kernel_us,
        baseline_us=req.baseline_us,
        plugin=req.plugin,
        spec_json=req.spec_json,
        function_name=req.function_name,
        scalar_args=req.scalar_args,
        gpu=req.gpu,
        postprocessed_source=req.postprocessed_source,
        python_registration=req.python_registration,
    )

    return {
        "id": kernel.id,
        "job_id": kernel.job_id,
        "plugin": kernel.plugin,
        "function_name": kernel.function_name,
        "kernel_us": kernel.kernel_us,
        "baseline_us": kernel.baseline_us,
        "speedup": kernel.baseline_us / kernel.kernel_us,
        "achieved_at": kernel.achieved_at.isoformat(),
    }


@kernels_router.get("/{kernel_id}")
def get_kernel_route(kernel_id: int, _principal: ApiPrincipal = Depends(require_api_key)):
    kernel = get_kernel(kernel_id)
    if kernel is None:
        raise HTTPException(404, "Kernel not found")
    return kernel


@kernels_router.patch("/{kernel_id}")
def update_kernel_route(
    kernel_id: int,
    postprocessed_source: str | None = None,
    python_registration: str | None = None,
    _principal: ApiPrincipal = Depends(require_admin_key),
):
    success = update_kernel_postprocessing(kernel_id, postprocessed_source=postprocessed_source, python_registration=python_registration)
    if success is False:
        raise HTTPException(404, "Kernel not found")
    return {"status": "updated"}


@kernels_router.post("/{kernel_id}/invalidate")
def invalidate_kernel_route(
    kernel_id: int,
    reason: str | None = None,
    _principal: ApiPrincipal = Depends(require_admin_key),
):
    success = invalidate_kernel(kernel_id, reason)
    if success is False:
        raise HTTPException(404, "Kernel not found")
    return {"status": "invalidated"}
